### ISSUE TITLE
Found argument '--server /app/config.toml' which wasn't expected with Docker compose

### ISSUE THREAD

**Issue by SirMishaa** [rapiz1/rathole#120]
Hello ! 

I'm trying to make a simple docker compose
```yml
services:
  rustrock:
    image: rapiz1/rathole:v0.3.9
    volumes:
      - ./config.toml:/app/config.toml
    command:
      - --server /app/config.toml
```

I got the following error message : 
> error: Found argument '--server /app/config.toml' which wasn't expected, or isn't valid in this context
2022-01-28T15:38:54.780018105Z 
2022-01-28T15:38:54.780021275Z 	Did you mean '--server'?
2022-01-28T15:38:54.780023805Z 
2022-01-28T15:38:54.780026335Z 	If you tried to supply `--server /app/config.toml` as a value rather than a flag, use `-- --server /app/config.toml`
2022-01-28T15:38:54.780029085Z 
2022-01-28T15:38:54.780031425Z USAGE:
2022-01-28T15:38:54.780034005Z     rathole --server <CONFIG|--genkey <CURVE>>
2022-01-28T15:38:54.780036895Z 
2022-01-28T15:38:54.780039465Z For more information try --help

Am I doing something wrong ? I'm sure, I just missed a thing
