### ISSUE TITLE
[Feature Request] One service forwards tcp and udp at the same time

### ISSUE THREAD

**Issue by chengziorange** [rapiz1/rathole#162]
When I want to expose a port at local machine listening both tcp and udp, I have to write two services in the config file like this:  
```toml
[client.services.service1_tcp]
type = "tcp"
token = "whatever"
local_addr = "127.0.0.1:1081"

[client.services.service1_udp]
type = "udp"
token = "whatever"
local_addr = "127.0.0.1:1081"
```
and do the same thing on the server side. I think a better way could be like this:  
```toml
[client.services.service1]
type = "tcp,udp" # Possible values: ["tcp", "udp", "tcp,udp"]
token = "whatever"
local_addr = "127.0.0.1:1081"
```
the above two config do the same thing, but the latter is more consice
