### ISSUE TITLE
Doesn't work behind Traefik

### ISSUE THREAD

**Issue by birkanozer** [rapiz1/rathole#169]
Hi there, 
I'm currently trying to manage all of my containers with Docker and Traefik. Rathole works perfectly with Docker alone. But when I try to add subdomains with Traefik it doesn't working at all. I provided my current docker-compose yaml files. 

traefik.yaml
```
version: '3.8'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - target: 2333 # <== rathole connect
        published: 2333
        mode: host # <== real ip aware
      - target: 5202 # <== rathole forward
        published: 5202
        mode: host # <== real ip aware

    command:
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.debug=true<== Enabling additional endpoints for debugging and profiling
     
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.docker.network=public-network # <== Operate on the docker network named public-network 

     - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web

      ## Rathole Entripoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.ratholeconnect.address=:2333 # <== Defining an entrypoint for rathole connect
      - --entrypoints.ratholeforward.address=:5202 # <== Defining an entrypoint for rathole forward
     
    networks:
      - public-network
      - 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - 
    labels:
      # Base settings
      - "traefik.enable=false" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.docker.network=public-network"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.traefik.service=api@internal" # <== Enabling the api to be a service to access
      - "traefik.http.routers.traefik.entrypoints=web"

networks:
  public-network:
    external: true
```

rathole.yaml
```
version: "3.8"

services: 
  rathole: 
    image: rapiz1/rathole
    volumes: 
      - /home/config.toml:/app/config.toml
    networks:
      - public-network
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    command: --server /app/config.toml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-network"
      - 
      # Control channel 
      - "traefik.tcp.routers.ratholeconnect.rule=Host(`mydomain.com`)"
      - "traefik.tcp.routers.ratholeconnect.entrypoints=ratholeconnect"
      - "traefik.tcp.routers.ratholeconnect.service=ratholeconnect-service"
      - "traefik.tcp.services.ratholeconnect-service.loadbalancer.server.port=2333" #random port number #2333
      # Forward channel 
      - "traefik.tcp.routers.ratholeforward.rule=Host(`rathole.mydomain.com`)" 
      - "traefik.tcp.routers.ratholeforward.entrypoints=ratholeforward"
      - "traefik.tcp.routers.ratholeforward.service=ratholeforward-service"
      - "traefik.tcp.services.ratholeforward-service.loadbalancer.server.port=5202" #random port number #5202
      
networks:
  public-network:
    external: true
```

server.toml
```
# server.toml
[server]
bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients

[server.services.srv1]
token = "use_a_secret_that_only_you_know" # Token that is used to authenticate the client for the service. 
bind_addr = "0.0.0.0:5202" # `5202` specifies the port that exposes `srv1` to the Internet
```

client.toml
```
# client.toml
[client]
remote_addr = "mydomain.com:2333" # The address of the server. The port must be the same with the port in `server.bind_addr`

[client.services.srv1]
token = "use_a_secret_that_only_you_know" # Must be the same with the server to pass the validation
local_addr = "192.168.1.40:8000" # The address of the service that needs to be forwarded
```

**Logs**
Server Logs
```
Jun 22 21:03:02.543 DEBUG rathole: Config { server: Some(ServerConfig { bind_addr: "0.0.0.0:2333", default_token: None, services: {"ssh": ServerServiceConfig { service_type: Tcp, name: "srv1", bind_addr: "0.0.0.0:5202", token: Some(MASKED), nodelay: None }}, transport: TransportConfig { transport_type: Tcp, tcp: TcpConfig { nodelay: false, keepalive_secs: 20, keepalive_interval: 8, proxy: None }, tls: None, noise: None }, heartbeat_interval: 30 }), client: None },
Jun 22 21:03:02.546  INFO rathole::server: Listening at 0.0.0.0:2333,
Jun 22 21:03:02.546  INFO config_watcher{path="/app/config.toml"}: rathole::config_watcher: Start watching the config
```

Client Logs
```
RUST_BACKTRACE=1 RUST_LOG=debug ./rathole client.toml
Jun 23 00:01:46.342 DEBUG rathole: Config { server: None, client: Some(ClientConfig { remote_addr: "mydomain.com:2333", default_token: None, services: {"srv1": ClientServiceConfig { service_type: Tcp, name: "srv1", local_addr: "192.168.1.40:8000", token: Some(MASKED), nodelay: None }}, transport: TransportConfig { transport_type: Tcp, tcp: TcpConfig { nodelay: false, keepalive_secs: 20, keepalive_interval: 8, proxy: None }, tls: None, noise: None }, heartbeat_timeout: 40 }) }
Jun 23 00:01:46.342  INFO handle{service=srv1}: rathole::client: Starting 7f5a55cf3f88be936fb9440249cb449f3067ccee4b525d0027dc9278a29c32c1
Jun 23 00:01:46.342  INFO config_watcher{path="client.toml"}: rathole::config_watcher: Start watching the config
Jun 23 00:01:46.391 DEBUG handle{service=srv1}:run: rathole::client: Sending hello
Jun 23 00:01:46.392 DEBUG handle{service=srv1}:run: rathole::client: Reading hello
```

**Environment:**
 - OS: Ubuntu Server (20.04.4 LTS (Focal Fossa)), Raspberry Pi OS (Debian GNU/Linux 11 (bullseye))
- `rathole --version` output: 0.4.1
- Docker version 20.10.16, build aa7e414, docker-compose version 1.27.4, build 40524192,

**Comment by rapiz1** [comment]
Thanks for the report. I have no experience using traefik. I will find time to reproduce this.

**Comment by AlekseyLobanov** [comment]
Hello. Another Traefik user here.

I just installed my first instance of rathole and it works with Docker auto-discovery, docker-compose and noise without problems.

I have two machines:
1. Server with rathole server and Traefik inside one docker-compose
2. Client with rathole client and my application inside another docker-compose.

Configs below:
```toml
[client]
remote_addr = "MY_DOMAIN_HERE:2714"
default_token = "TOKEN"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "KEY"

[client.services.baikal]
local_addr = "baikal:80"
```
and server
```toml
[server]
bind_addr = "0.0.0.0:2714"
default_token = "TOKEN"

[server.transport]
type = "noise"
[server.transport.noise]
local_private_key = "KEY"

[server.services.baikal]
bind_addr = "0.0.0.0:5263"
```
*NB:* I use docker DNS for my client container instead of IP

For server compose I use something like this:
```yaml
version: '3'
services:
  rathole:
    image: rapiz1/rathole
    command: /config.toml
    restart: unless-stopped
    volumes:
      - /home/alex/main-compose/rathole-config.toml:/config.toml:ro
    ports:
      - "2714:2714"
     # - "5263:5263"  # baikal was here
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=https"
      - "traefik.http.routers.baikal.rule=Host(`baikal.example.com`)"
      - "traefik.http.routers.baikal.tls=true"
      - "traefik.http.routers.baikal.tls.certresolver=letsEncrypt"
      - "traefik.http.services.baikal.loadbalancer.server.port=5263"
```

**Comment by birkanozer** [comment]
Hi @AlekseyLobanov ,

Did you try to forward 2714 port with Traefik too?

**Comment by AlekseyLobanov** [comment]
> Did you try to forward 2714 port with Traefik too?

No. I believe it may be something like anti-pattern for most cases. 
 - We don't need HTTPS for rathole, because it has noise protocol support.
 - It works over low-level protocols, HTTP path operations are useless.

**Comment by nemanjam** [comment]
Traefik should be in local network (not on VPS) for many reasons.

**Comment by AlekseyLobanov** [comment]
Can you write some of this reasons here? I believe it was one of intended use cases. For example it has let's encrypt integration which of course can't work inside local network (almost always of course)
![architecture](https://traefik.io/static/cae24a096347440831830b776f4362bc/bac8a/diagram%403x.webp)

**Comment by nemanjam** [comment]
https://blog.mni.li/posts/caddy-rathole-zero-knowledge/

**Comment by raphpa** [comment]
You can also have the best of both worlds and use a tcp router with Traefik.

With the example above, assume you have your app behind Traefik in your internal network and want to make it available externally under another domain, if it works with that setup.

Let the internal Traefik create a certificate for the external domain as well and make the app listen to the external domain in addition to the internal domain.

```yaml
services:
  traefik:
    image: traefik
    command: >
      --log.level=INFO
      
      ...

      --entryPoints.https.http.tls.certresolver=letsencrypt
      --entryPoints.https.http.tls.domains[0].main=internal.com
      --entryPoints.https.http.tls.domains[0].sans=*.internal.com
      --entryPoints.https.http.tls.domains[1].main=baikal.external.com

      ...

````

```yaml
services:
  baikal:
    image: baikal

    ...

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=https"
      - "traefik.http.routers.baikal.rule=Host(`baikal.internal.com`) || Host(`baikal.external.com`)"
      - "traefik.http.routers.baikal.tls=true"
      - "traefik.http.routers.baikal.tls.certresolver=letsEncrypt"
      - "traefik.http.services.baikal.loadbalancer.server.port=5263"
```

Create a rathole configuration that tunnels the internal Traefik instance to the external server.

```toml
[server]
bind_addr = "0.0.0.0:2714"
default_token = "TOKEN"

[server.transport]
type = "noise"
[server.transport.noise]
local_private_key = "KEY"

[server.services.baikal]
bind_addr = "0.0.0.0:55555"
```

```toml
[client]
remote_addr = "external.com:2714"
default_token = "TOKEN"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "KEY"

[client.services.baikal]
local_addr = "127.0.0.1:443"
```
 
 
Configure rathole docker with Traefik labels that create a tcp router from the external domain/Traefik instance to the tunnel endpoint with tls passthrough enabled. The tls connection will be terminated by the internal Traefik instance.

```yaml
services:
  rathole:
    image: rapiz1/rathole
    command: --server /config.toml
    restart: unless-stopped

    volumes:
      - ./config.toml:/config.toml:ro

    ports:
      - "2714:2714"

    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.baikal.entrypoints=https"
      - "traefik.tcp.routers.baikal.rule=HostSNI(`baikal.external.com`)"
      - "traefik.tcp.routers.baikal.tls.passthrough=true"
      - "traefik.tcp.services.baikal.loadbalancer.server.port=55555"
```
