### ISSUE TITLE
Windows remote desktop optimization

### ISSUE THREAD

**Issue by raycke** [rapiz1/rathole#209]
**Feature Proposed**
Hi,

Deploy rathole and frp servers on the same cloud server (2 cores 8G, network bandwidth 100M). The test found that when penetrating the intranet Windows remote desktop, frp performed more stably and felt that the operation was smoother. Is it because frp can enable compression? But the 100M server bandwidth should not have a bandwidth bottleneck?

Here are my rathole and frp configuration files

rather server:
```toml
# server.toml
[server]
bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients
default_token = "xXwBD9NehlLO0xV3"

[server.services.office_windows_remote]
# token = "use_a_secret_that_only_you_know" # Token that is used to authenticate the client for the service. Change to a arbitrary value.
bind_addr = "0.0.0.0:3389" # `5202` specifies the port that exposes `my_nas_ssh` to the Internet
```

rather client:
```toml
# client.toml
[client]
remote_addr = "my server ip:2333" # The address of the server. The port must be the same with the port in `server.bind_addr`

[client.services.office_windows_remote]
token = "xXwBD9NehlLO0xV3" # Must be the same with the server to pass the validation
local_addr = "127.0.0.1:3389" # The address of the service that needs to be forwarded
```

frp server:
```ini
[common]
bind_port = 7000
token = xXwBD9NehlLO0xV3
```

frp client:
```ini
[common]
server_addr = my server ip
server_port = 7000
token = xXwBD9NehlLO0xV3

[office_windows_remote]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 13389
use_compression = true
```

**Use Case**

Best Regards.
