### ISSUE TITLE
[Docker] Configure with env vars

### ISSUE THREAD

**Issue by williamhatcher** [rapiz1/rathole#218]
**Feature Proposed**
Is it possible to allow configuration via env vars in the docker image, or something other than a file?

**Use Case**
Running rathole in a Portainer instance. Portainer doesn't allow you to attach files to a docker compose stack.

**Comment by rapiz1** [comment]
This is a very interesting idea. But given the rathole configuration format is not trivial, how can you do that in env vars?  Do you have any proposals? Maybe we can pass config string in a single env var but I wonder if there's a length limit for env var that renders many configurations unpractical.

**Comment by Skaronator** [comment]
A quick google search says that there is basically no length limit for this usecase. Some results say around 32k characters on Windows, while linux has over 256 MB per/for all? Environment variables. Basically, endless for this usecase.

I'd suggest that `.` is replaced by one `_` and [header] and configBody seperated by two `__`:

```toml
[client]
remote_addr = "example.cm"
default_token = "xyz"

[client.transport]
type = "noise"

[client.transport.noise]
pattern = "Noise_KK_25519_ChaChaPoly_BLAKE2s"

[client.services.http]
local_addr = "ingress-nginx-public-controller:80"

[client.services.https]
local_addr = "ingress-nginx-public-controller:443"
```

```bash

CLIENT__REMOTE_ADDR = "example.cm"
CLIENT__DEFAULT_TOKEN = "xyz"

CLIENT_TRANSPORT__TYPE = "noise"

CLIENT_TRANSPORT_NOISE__PATTERN = "Noise_KK_25519_ChaChaPoly_BLAKE2s"

CLIENT_SERVICES_HTTP__LOCAL_ADDR = "ingress-nginx-public-controller:80"

CLIENT_SERVICES_HTTPS__LOCAL_ADDR = "ingress-nginx-public-controller:443"


```
