### ISSUE TITLE
Wireguard support

### ISSUE THREAD

**Issue by AlexZorzi** [rapiz1/rathole#261]
**Describe the bug**
Im not able to setup a connection with wireguard through rathole.

**To Reproduce**
1.  setup wireguard (weejewel/wg-easy) on the server and rathole
2.  create a configuration file for a wireguard peer and try to connect

**Configuration**
```
version: '3.3'
services:
    rathole:
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '2333:2333'
            - '51820:51820'
        volumes:
            - '/root/config.toml:/app/config.toml'
        image: rapiz1/rathole
        entrypoint: "./rathole --server /app/config.toml"

```

```
# server.toml
[server]
bind_addr = "0.0.0.0:2333" 

[server.services.wireguard]
token = "**********************"
bind_addr = "0.0.0.0:51820"
```

```
[client]
remote_addr = "******:2333"
default_token = "**********************" 
heartbeat_timeout = 40
retry_interval = 1

[client.services.wireguard]
type = "udp"
local_addr = "******:51820"
nodelay = true
retry_interval = 1

```

**Logs**
Wireguard app gets stuck at the handshake init

**Environment:**
 - OS: Debian
- `rathole --version` output: 0.4.8
- CPU architecture: x64

**Comment by fernvenue** [comment]
Can't reproduce, my WireGuard works great with rathole, is your WireGuard works without rathole? By the way, in your server configuration:

```
[server.services.wireguard]
token = "**********************"
bind_addr = "0.0.0.0:51820"
```

You may need to define `type` as `udp`.

**Comment by AlexZorzi** [comment]
> Can't reproduce, my WireGuard works great with rathole, is your WireGuard works without rathole? By the way, in your server configuration:
> 
> ```
> [server.services.wireguard]
> token = "**********************"
> bind_addr = "0.0.0.0:51820"
> ```
> 
> You may need to define `type` as `udp`.

Can you share your configuration? My setup is a bit weird as my server (rathole client) only has a static IPv6 and a natted Ipv4 so wireguard should go through a vps (rathole server). I thought the type on the client config would have been enough but I will try to add it to the server config as well

**Comment by fernvenue** [comment]
> Can you share your configuration?

Sure, here's my configuration for WireGuard:

```
[server.services.wireguard]
type = "udp"
bind_addr = "0.0.0.0:9573"

[client.services.wireguard]
type = "udp"
local_addr = "127.0.0.1:9573"
```

By the way, as I said above, make sure your WireGuard works well without rathole, that's the first thing, so that we can know which part goes wrong.

**Comment by AlexZorzi** [comment]
Added the udp part on the server as well but with no luck in connecting, i use other ports like 443 and 80 without issues

> By the way, as I said above, make sure your WireGuard works well without rathole, that's the first thing, so that we can know which part goes wrong.

i tried and it works locally, i only have issues when trying to go through rathole

**Comment by fernvenue** [comment]
Could you please provide your log info?

**Comment by AlexZorzi** [comment]
> It should be something there in log even if the service not connected, what exactly configuration file do you use?

this is my full server configuration

```
# server.toml
[server]
bind_addr = "0.0.0.0:2333"

[server.services.ssh]
token = "secretkey"
bind_addr = "0.0.0.0:2222"

[server.services.http]
token = "secretkey"
bind_addr = "0.0.0.0:80"

[server.services.wireguard]
type = "udp"
token = "secretkey"
bind_addr = "0.0.0.0:666"

[server.services.https]
token = "secretkey"
bind_addr = "0.0.0.0:443"

```
docker-compose.yml
```
version: '3.3'
services:
    rathole:
        environment:
            - RUST_LOG=debug
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '2333:2333'
            - '2222:2222'
            - '666:666'
        volumes:
            - './config.toml:/app/config.toml'
        image: rapiz1/rathole
        entrypoint: "./rathole --server /app/config.toml"
```
