### ISSUE TITLE
I encountered an error while trying to proxy HTTPS and HTTP services.

### ISSUE THREAD

**Issue by vicnoah** [rapiz1/rathole#262]
I keep getting "Permission denied" when trying to use rothole to proxy ports 80 and 443.

2023-06-12T03:22:10.986117Z ERROR connection{addr=xx}:handle{service=1panel-https}:run_tcp_connection_pool: rathole::server: Permission denied (os error 13). Retry in 870.224686ms

docker-compose.yaml
```
version: '3.3'
services:
    rathole:
        image: rapiz1/rathole:v0.4.8
        restart: always
        cap_add:
          - NET_ADMIN
        command: --server /app/config.toml
        ports:
            - '80:80'
            - '443:443'
            - '33080:33080'
            - '34000:34000'
        volumes:
            - $PWD/config.toml:/app/config.toml
```

**Comment by vypxl** [comment]
I have the same issue, how did you solve it?

**Comment by fernvenue** [comment]
> I have the same issue, how did you solve it?

Hi, could you please provide any details or log information?

**Comment by vypxl** [comment]
Sorry, I ended up using a different solution instead of rathole, I use a wireguard tunnel now.

**Comment by Skaronator** [comment]
I ran in the same issue. The problem is most likely that the user 1000:1000 (from the Dockerfile) doesn't have permission to open 80 and 443 port.

One (bad) solution to this issue would be to use a user with enough permissions. For example, set `user: root` in your docker-compose file fixes this.

**Comment by Skaronator** [comment]
Got it working. Make sure the config file owns 1000:1000 then this will work:

```yaml
version: '3.8'
services:
  rathole:
    image: rapiz1/rathole:v0.5.0
    container_name: rathole
    volumes:
    - /srv/config/rathole.toml:/app/config.toml
    ports:
    - '80:80'
    - '443:443'
    command:
    - "--server"
    - "/app/config.toml"
    restart: always
```
