### ISSUE TITLE
Allow use of DNS reolution from proxy server

### ISSUE THREAD

**Issue by bvanelli** [rapiz1/rathole#288]
**Feature Proposed**

Currently, you can connect through an HTTP proxy using the following config:

```
[client.transport]
type = "tcp"
[client.transport.tcp]
proxy = "http://proxy:3128"
```

But this only works if the domain name can be resolved by the host, not by the proxy. When setting the docker-compose with the extra host, it then works:

```yaml
  bridge:
    # image: rapiz1/rathole:latest
    build: rathole/
    restart: always
    networks: ["edge"]
    container_name: bridge
    command: /app/config.toml
    extra_hosts: ["tunnel:172.19.0.3"]
    volumes:
      - "./rathole/application.toml:/app/config.toml"
    ports:
      - "8080:8080"
 ```

Since it's a PoC I fixed the internal IP.

**Use Case**

When the proxy is desired, but DNS resolution also has to go throught the proxy.

**Possible Solution**

I believe the proxy library in use is https://github.com/LinkTed/async-http-proxy, and therefore does not implement this feature of proxying dns requests. The general behaviour would be:

- Add option proxy_dns = auto (default), local or proxy
- When on automatic, try to resolve locally, if fails, try to resolve on proxy server
- When on local, only use local dns resolution (current behaviour)
- When on proxy, only use proxy dns resolution

My Rust knowlege is very limited but it seems like the type of feature I could implement, if you say it's feasible using currently libraries and no major refactor is required.
