### ISSUE TITLE
OS can't spawn a new worker thread

### ISSUE THREAD

**Issue by Chuckame** [rapiz1/rathole#319]
**Describe the bug**

Using the official docker image, I get fatal error because of OS can't spawn a new worker thread.

To fix it, I need to add the following (coming from https://github.com/vadimcn/codelldb/issues/674):
```
    security_opt:
      - "seccomp=unconfined"
```
After adding the security opt, the error disappear and it works but I need to run the server as root to make it work.

**To Reproduce**
docker-compose.yml file:
```yaml
version: "3.8"
services:
  home-tunnel-server:
    image: rapiz1/rathole:v0.5.0
    restart: unless-stopped
    command: --server /config/server.toml
    ports:
      - 7001:7001 # server port
    volumes:
      - ./config/rathole/server.toml:/config/server.toml:ro
```

**Logs**

```
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:13
stack backtrace:
   0:     0x7f5ae03ddb01 - <unknown>
   1:     0x7f5ae027132f - <unknown>
   2:     0x7f5ae03b66f6 - <unknown>
   3:     0x7f5ae03df7df - <unknown>
   4:     0x7f5ae03deee0 - <unknown>
   5:     0x7f5ae03e0077 - <unknown>
   6:     0x7f5ae03dfa72 - <unknown>
   7:     0x7f5ae03df9d6 - <unknown>
   8:     0x7f5ae03df9c1 - <unknown>
   9:     0x7f5ae01328a2 - <unknown>
  10:     0x7f5ae021d347 - <unknown>
  11:     0x7f5ae01519e3 - <unknown>
  12:     0x7f5ae0229f3b - <unknown>
  13:     0x7f5adf9871ca - <unknown>
  14:     0x7f5adf987285 - __libc_start_main
  15:     0x7f5ae0148535 - <unknown>
  16:                0x0 - <unknown>
```

**Environment:**
- Docker container
- rathole version: `v0.5.0`
- Operating System: Debian GNU/Linux 10 (buster)
- Kernel: Linux 4.19.0-24-amd64
- Architecture: x86-64
