### ISSUE TITLE
Support SOCKS5_PROXY and HTTP_PROXY for transport

### ISSUE THREAD

**Issue by rapiz1** [rapiz1/rathole#35]
Like:

```toml
[client.transport]
type = "tcp"
[client.transport.tcp]
proxy = "socks5://localhost:1080" # connect to the server via a socks5 proxy
```

or
```toml
[client.transport]
type = "tcp"
[client.transport.tcp]
proxy = "http://localhost:1080" # connect to the server via a http proxy
```
