### ISSUE TITLE
Slow TCP throughput Minecraft server

### ISSUE THREAD

**Issue by BrammyS** [rapiz1/rathole#370]
**Describe the bug**

I am experiencing a severe slow down of network traffic when using Rathole for a Minecraft server.
The proxy server has a multi Gbit/s connection and our local connection is 1 Gbit/s, so this can not be an issue. I have also tried an iperf3 test with with the same configurations and it showed nothing out of the ordinary. What could be the issue here?

- Network traffic in Minecraft when connected locally
![byKkXY2KeLEOv4sMmu9WPaf8Sm4mgzHZTuKNWuv6vblUWrH77LQs6YyfMaKEr3CH](https://github.com/rapiz1/rathole/assets/35614609/1851f0ce-5c8f-4edd-9f1b-8e1d8aa3fe64)
- Network traffic in Minecraft when connected through Rathole
![QxZjDp7aqTw8flaoyVL404elKT9bnysOQE2CrLhpM1IJ6uDJvJhJdOvINbYDvQuc](https://github.com/rapiz1/rathole/assets/35614609/8b768f5c-fb76-4f5f-9d34-6a8da7e4af65)

**To Reproduce**
1. Server config
```toml
[server]
bind_addr = "0.0.0.0:2333"
default_token = "xxx"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "xxx"

[server.services.mc]
bind_addr = "0.0.0.0:25565"
```
2. Client config
```toml
[client]
remote_addr = "0.0.0.0:2333"
default_token = "xxx"

[client.transport]
type = "noise"

[client.transport.noise]
remote_public_key = "xxx"

[client.services.mc]
local_addr = "10.0.1.5:25565"
```
3. Docker-compose file

```yaml
services:
  rathole:
    image: 'arm64-rathole'
    container_name: rathole
    restart: unless-stopped
    ports:
      - "2333:2333" # Only present on the server side
      - "25565:25565" # Only present on the server side
    volumes:
      - './config.toml:/app/config.toml'
    command:
      - '/app/config.toml'
    networks:
      tunnel:
        ipv4_address: 10.0.1.2
  mc: # Only present on client side
    ....
    ports:
      - "25565:25565" # Only present on the client side, used to connect directly to it.
    networks:
      tunnel:
        ipv4_address: 10.0.1.5

networks:
  tunnel:
    external: true
```

**Configuration**
Configuration used to reproduce the behavior:

**Logs**

**Environment:**
 - OS: Ubunut-22.04
- `rathole --version`: I am using the latest [v0.5.0](https://hub.docker.com/layers/rapiz1/rathole/v0.5.0/images/sha256-52f3a087ccb89358705de1f6ac0e923a00d066fe9a8548ab7a79ad21adab93fa?context=explore) docker image.
- CPU architecture: amd64
- rustc version: -
