### ISSUE TITLE
ERROR: rathole::config_watcher: The changed configuration is invalid. Ignored: Configuration is invalid. Please refer to the configuration specification.: Failed to parse the config: redefinition of table `server.services.mcbedrock` for key

### ISSUE THREAD

**Issue by AlexPewMaster** [rapiz1/rathole#375]
**Describe the bug**

Whenever I try adding the UDP port 19132 to the rathole server configuration, rathole throws up errors about this: `Jun 21 13:20:12 fedora-vps rathole[4622]: 2024-06-21T13:20:12.804641Z ERROR config_watcher{path="/etc/rathole/server.toml"}: rathole::config_watcher: The changed configuration is invalid. Ignored: Configuration is invalid. Please refer to the configuration specification.: Failed to parse the config: redefinition of table server.services.blueberry_mcbedrock for key server.services.blueberry_mcbedrock at line 138 column 1`

**To Reproduce**
1. Create a server config file with the content below and save as `server.toml`
2. Run rathole with `rathole -s server.toml`
3. See error

**Configuration**
Configuration used to reproduce the behavior:
```toml
[server]
bind_addr = "0.0.0.0:2333"
default_token = "REDACTED"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "REDACTED"

# There are a lot of other things here, I left them out because they're unrelated to the issue

[server.services.blueberry_mcbedrock]
type = "udp"
bind_addr = "0.0.0.0:19132"
```

**Logs**

```
Jun 21 13:20:12 fedora-vps rathole[4622]: 2024-06-21T13:20:12.784133Z  INFO config_watcher{path="/etc/rathole/server.toml"}: rathole::config_watcher: Rescan the configuration
Jun 21 13:20:12 fedora-vps rathole[4622]: 2024-06-21T13:20:12.804641Z ERROR config_watcher{path="/etc/rathole/server.toml"}: rathole::config_watcher: The changed configuration is invalid. Ignored: Configuration is invalid. Please refer to the configuration specification.: Failed to parse the config: redefinition of table `server.services.blueberry_mcbedrock` for key `server.services.blueberry_mcbedrock` at line 138 column 1
```

**Environment:**
 - OS: Fedora Linux 39
- `rathole --version` output:
```
rathole 
Build Timestamp:     2023-10-01T09:59:43.840042255Z
Build Version:       0.5.0
Commit SHA:          Some("ebb764ae53d7ffe4fcb45f83f7563bec5c74199d")
Commit Date:         Some("2023-10-01T09:55:18Z")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: aarch64-unknown-linux-musl
cargo Profile:       release
cargo Features:      base64,client,embedded,hot_reload,noise,notify,server,snowstorm
```
- CPU architecture: aarch64 / ARM64
- rustc version: Unknown
