### ISSUE TITLE
Why each server.services need to bind an port while client didn't need this port

### ISSUE THREAD

**Issue by lucasjinreal** [rapiz1/rathole#399]
Hi

I found this is hard to understanding compare with frp.

```toml
[server]
bind_addr = "0.0.0.0:7000" # `2333` specifies the port that rathole listens for clients

[server.services.my_nas_ssh]
token = "xx" # Token that is used to authenticate the client for the service. Change to an arbitrary value.
bind_addr = "0.0.0.0:8080" # `5202` specifies the port that exposes `my_nas_ssh` to the Internet

[server.services.fhh]
token = "xx" # Token that is used to authenticate the client for the service. Change to an arbitrary value.
bind_addr = "0.0.0.0:8081" # `5202` specifies the port that exposes `my_nas_ssh` to the Internet
```

the server bind port is understandable, but why each services need to bind differnt port? 
When I using frp, there only 2 ports for all clients, and it can specific customized domain.

How could I do this simmilar to rathole
